name: Release with Artifacts

on:
  push:
    tags: ["v*.*.*"] # Trigger on tag pushes (adjust the pattern as needed)

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: Compile Windows
        id: compile-windows
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
          ARCHIVE_TYPES: zip

      - name: copy checksum
        uses: canastro/copy-file-action@master
        with:
          source: ${{ steps.compile-windows.outputs.BUILT_CHECKSUM }}
          target: "windows.sha256"

      - name: Compile Linux
        id: compile-linux
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          ARCHIVE_TYPES: tar.gz

      - name: copy checksum
        uses: canastro/copy-file-action@master
        with:
          source: ${{ steps.compile-linux.outputs.BUILT_CHECKSUM }}
          target: "linux.sha256"

      - name: Compile MacOS
        id: compile-macos
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-apple-darwin
          UPLOAD_MODE: none
          ARCHIVE_TYPES: zip

      - name: copy checksum
        uses: canastro/copy-file-action@master
        with:
          source: ${{ steps.compile-macos.outputs.BUILT_CHECKSUM }}
          target: "macos.sha256"

      - name: Download files
        run: |
          wget https://storage.googleapis.com/nuteksecurity-public/NutekCipherMacOS.zip -O NutekCipherMacOS.zip
          wget https://storage.googleapis.com/nuteksecurity-public/NutekCipherMacOS.zip.sha256 -O NutekCipherMacOS.zip.sha256
          # Add more wget commands for more files

      - name: remove artifacts from sha256sum
        id: sha
        run: |
          BASE_NAME=${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}
          sed 's/output\///g' windows.sha256 > "${BASE_NAME##*/}.sha256"
          export WINDOWS_SHA="${BASE_NAME##*/}.sha256"
          BASE_NAME=${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
          sed 's/output\///g' linux.sha256 > "${BASE_NAME##*/}.sha256"
          export LINUX_SHA="${BASE_NAME##*/}.sha256"
          BASE_NAME=${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}
          sed 's/output\///g' macos.sha256  > "${BASE_NAME##*/}.sha256"
          export MACOS_SHA="${BASE_NAME##*/}.sha256"

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          draft: true
          automatic_release_tag: "latest"
          prerelease: false
          title: "CLI for your Shadowheart"
          files: |
            NutekCipherMacOS.zip
            NutekCipherMacOS.zip.sha256
            ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}
            ${{ steps.sha.env.WINDOWS_SHA }}
            ${{ steps.sha.env.LINUX_SHA }}
            ${{ steps.sha.env.MACOS_SHA }}
