name: Release with Artifacts

on:
  push: 
    #tags: [ "v*.*.*" ]  # Trigger on tag pushes (adjust the pattern as needed)

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      # - name: Build
      #   run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: Set permissions
        run: mkdir output && chmod -R 777 output

      - name: Compile Windows
        id: compile-windows
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-pc-windows-gnu
          UPLOAD_MODE: none
          ARCHIVE_TYPES: zip

      - name: Checksum windows
        run: |
          sha256sum ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }} > ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}.sha256

      - name: Compile Linux
        id: compile-linux
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          ARCHIVE_TYPES: tar.gz tar.xz tar.zst

      - name: Checksum linux
        run: |
          sha256sum ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }} > ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}.sha256
  
      - name: Compile MacOS
        id: compile-macos
        uses: rust-build/rust-build.action@v1.4.3
        with:
          RUSTTARGET: x86_64-apple-darwin
          UPLOAD_MODE: none
          ARCHIVE_TYPES: zip

      - name: Checksum macos
        run: |
          sha256sum ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }} > ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}.sha256
          # Add more checksum commands for more files
  
      - name: Download files
        run: |
          wget https://storage.googleapis.com/nuteksecurity-public/NutekCipherMacOS.zip -O NutekCipherMacOS.zip
          wget https://storage.googleapis.com/nuteksecurity-public/NutekCipherMacOS.zip.sha265 -O NutekCipherMacOS.zip.sha265
          # Add more wget commands for more files

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          draft: true
          automatic_release_tag: "latest"
          prerelease: false
          title: "CLI for your Shadow..."
          files: |
            NutekCipherMacOS.zip
            NutekCipherMacOS.zip.sha265
            ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-windows.outputs.BUILT_ARCHIVE }}.sha256
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-linux.outputs.BUILT_ARCHIVE }}.sha256
            ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile-macos.outputs.BUILT_ARCHIVE }}.sha256